### ISSUE TITLE
Problems with `@libp2p/devtools-metrics/rpc` import

### ISSUE THREAD

**Issue by d-roak** [ipfs-shipyard/js-libp2p-devtools#4]
<img width="958" alt="image" src="https://github.com/user-attachments/assets/a3d78a98-b80e-4314-b2d7-e83a7b98cf54">

After:
1. Cloning
2. `npm i`
3. `npm build`

Node version: 20.16.0
Npm version: 10.8.1

**Comment by SgtPooki** [comment]
@d-roak thanks for reporting this bug! sorry for the delay, we will be looking into this shortly.

**Comment by 2color** [comment]
Hey @d-roak, can you try https://github.com/ipfs-shipyard/js-libp2p-devtools/pull/6?

**Comment by d-roak** [comment]
yep, #6 fixes the issue 🫡

**Comment by d-roak** [comment]
![image](https://github.com/user-attachments/assets/4c1803e1-e303-4178-bcdd-800008ae10e1)

rocking with it
